"""initial schema

Revision ID: 4dd57d68b4fa
Revises:
Create Date: 2026-05-18 16:07:26.150120

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dd57d68b4fa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tradingsymbol", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("alert_type", sa.String(length=20), nullable=False),
        sa.Column("target_value", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_tradingsymbol"), "alerts", ["tradingsymbol"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=50), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_events_entity_type"), "audit_events", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False)
    op.create_table(
        "behavior_flags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flag_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=True),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_behavior_flags_flag_type"), "behavior_flags", ["flag_type"], unique=False)
    op.create_index(op.f("ix_behavior_flags_trade_id"), "behavior_flags", ["trade_id"], unique=False)
    op.create_table(
        "holdings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tradingsymbol", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("isin", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("average_price", sa.Float(), nullable=False),
        sa.Column("last_price", sa.Float(), nullable=False),
        sa.Column("pnl", sa.Float(), nullable=False),
        sa.Column("day_change", sa.Float(), nullable=False),
        sa.Column("day_change_pct", sa.Float(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holdings_tradingsymbol"), "holdings", ["tradingsymbol"], unique=False)
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("instrument_token", sa.BigInteger(), nullable=False),
        sa.Column("exchange_token", sa.BigInteger(), nullable=False),
        sa.Column("tradingsymbol", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("segment", sa.String(length=20), nullable=False),
        sa.Column("instrument_type", sa.String(length=20), nullable=False),
        sa.Column("lot_size", sa.Integer(), nullable=False),
        sa.Column("tick_size", sa.Float(), nullable=False),
        sa.Column("expiry", sa.String(length=20), nullable=True),
        sa.Column("strike", sa.Float(), nullable=True),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_instruments_exchange"), "instruments", ["exchange"], unique=False)
    op.create_index(op.f("ix_instruments_instrument_token"), "instruments", ["instrument_token"], unique=False)
    op.create_index(op.f("ix_instruments_tradingsymbol"), "instruments", ["tradingsymbol"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=True),
        sa.Column("tradingsymbol", sa.String(length=50), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_journal_entries_trade_id"), "journal_entries", ["trade_id"], unique=False)
    op.create_index(op.f("ix_journal_entries_tradingsymbol"), "journal_entries", ["tradingsymbol"], unique=False)
    op.create_table(
        "order_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("tradingsymbol", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("transaction_type", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("trigger_price", sa.Float(), nullable=True),
        sa.Column("product", sa.String(length=10), nullable=False),
        sa.Column("order_type", sa.String(length=10), nullable=False),
        sa.Column("condition", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_rules_tradingsymbol"), "order_rules", ["tradingsymbol"], unique=False)
    op.create_table(
        "risk_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.String(length=10), nullable=False),
        sa.Column("total_invested", sa.Float(), nullable=False),
        sa.Column("total_current", sa.Float(), nullable=False),
        sa.Column("total_pnl", sa.Float(), nullable=False),
        sa.Column("day_pnl", sa.Float(), nullable=False),
        sa.Column("max_single_stock_pct", sa.Float(), nullable=False),
        sa.Column("sector_concentration", sa.JSON(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risk_snapshots_snapshot_date"), "risk_snapshots", ["snapshot_date"], unique=False)
    op.create_table(
        "sector_maps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tradingsymbol", sa.String(length=50), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sector_maps_sector"), "sector_maps", ["sector"], unique=False)
    op.create_index(op.f("ix_sector_maps_tradingsymbol"), "sector_maps", ["tradingsymbol"], unique=True)
    op.create_table(
        "tax_lots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tradingsymbol", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("buy_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("buy_price", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("remaining_quantity", sa.Integer(), nullable=False),
        sa.Column("sell_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sell_price", sa.Float(), nullable=True),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("holding_type", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tax_lots_tradingsymbol"), "tax_lots", ["tradingsymbol"], unique=False)
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.String(length=50), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=50), nullable=False),
        sa.Column("tradingsymbol", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("transaction_type", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("product", sa.String(length=10), nullable=False),
        sa.Column("order_type", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("traded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trades_order_id"), "trades", ["order_id"], unique=False)
    op.create_index(op.f("ix_trades_tradingsymbol"), "trades", ["tradingsymbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_tradingsymbol"), table_name="trades")
    op.drop_index(op.f("ix_trades_order_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_tax_lots_tradingsymbol"), table_name="tax_lots")
    op.drop_table("tax_lots")
    op.drop_index(op.f("ix_sector_maps_tradingsymbol"), table_name="sector_maps")
    op.drop_index(op.f("ix_sector_maps_sector"), table_name="sector_maps")
    op.drop_table("sector_maps")
    op.drop_index(op.f("ix_risk_snapshots_snapshot_date"), table_name="risk_snapshots")
    op.drop_table("risk_snapshots")
    op.drop_index(op.f("ix_order_rules_tradingsymbol"), table_name="order_rules")
    op.drop_table("order_rules")
    op.drop_index(op.f("ix_journal_entries_tradingsymbol"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_trade_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_instruments_tradingsymbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_instrument_token"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_exchange"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_holdings_tradingsymbol"), table_name="holdings")
    op.drop_table("holdings")
    op.drop_index(op.f("ix_behavior_flags_trade_id"), table_name="behavior_flags")
    op.drop_index(op.f("ix_behavior_flags_flag_type"), table_name="behavior_flags")
    op.drop_table("behavior_flags")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_alerts_tradingsymbol"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
