import jsPDF from "jspdf";
import type { Signal } from "../types/scanner";

const TIMEFRAME_LABELS: Record<string, string> = {
  "15minute": "Intraday 15m",
  day: "Daily",
  "5minute": "5m",
  "30minute": "30m",
};

export function exportSignalsPdf(signals: Signal[]): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 15) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Top Scanner Signals", margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated: ${new Date().toLocaleString("en-IN")}  |  ${signals.length} signal(s)`,
    margin,
    y,
  );
  doc.setTextColor(0, 0, 0);
  y += 10;

  signals.forEach((s, idx) => {
    checkPage(50);

    // Signal header bar
    const headerH = 8;
    const isBuy = s.signal_type === "BUY";
    doc.setFillColor(isBuy ? 220 : 254, isBuy ? 252 : 226, isBuy ? 231 : 226);
    doc.rect(margin, y - 5, contentWidth, headerH, "F");

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(isBuy ? 22 : 185, isBuy ? 101 : 28, isBuy ? 52 : 28);
    doc.text(
      `${idx + 1}. ${s.tradingsymbol}  —  ${s.signal_type}`,
      margin + 2,
      y,
    );

    const tfLabel =
      TIMEFRAME_LABELS[s.timeframe] || s.timeframe;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(tfLabel, pageWidth - margin - 2, y, { align: "right" });
    doc.setTextColor(0, 0, 0);
    y += headerH + 2;

    // Price row
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const priceText = `Entry: ${s.entry_price.toFixed(2)}    SL: ${s.stop_loss.toFixed(2)}    Target: ${s.target_price.toFixed(2)}    Confidence: ${s.confidence.toFixed(1)}%`;
    doc.text(priceText, margin + 2, y);
    y += 6;

    // Rationale
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    const lines = doc.splitTextToSize(s.rationale, contentWidth - 4);
    for (const line of lines) {
      checkPage(5);
      doc.text(line, margin + 2, y);
      y += 4;
    }
    doc.setTextColor(0, 0, 0);

    // Created time
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Signal generated: ${new Date(s.created_at).toLocaleString("en-IN")}`,
      margin + 2,
      y,
    );
    doc.setTextColor(0, 0, 0);
    y += 8;

    // Separator line
    if (idx < signals.length - 1) {
      doc.setDrawColor(220, 220, 220);
      doc.line(margin, y - 3, pageWidth - margin, y - 3);
    }
  });

  // Footer
  checkPage(10);
  y += 4;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Disclaimer: These signals are generated by automated technical analysis. Not financial advice. Do your own research.",
    margin,
    y,
  );

  doc.save(`scanner-signals-${new Date().toISOString().slice(0, 10)}.pdf`);
}
